//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BymaFixTester.WinForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INOM_Inversiones : DbContext
    {
        public INOM_Inversiones()
            : base("name=INOM_Inversiones")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BymaTrades> BymaTrades { get; set; }
        public virtual DbSet<BymaTradeCaptureReport> BymaTradeCaptureReport { get; set; }
    }
}
