//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BymaFixTester.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BymaTradeCaptureReport
    {
        public int BymaTradeCaptureReportID { get; set; }
        public string MsgType { get; set; }
        public string Currency { get; set; }
        public string IDSource { get; set; }
        public Nullable<double> LastPx { get; set; }
        public Nullable<int> LastShares { get; set; }
        public string SecurityID { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.DateTime> TransactTime { get; set; }
        public string SettlmntTyp { get; set; }
        public string FutSettDate { get; set; }
        public string ExecType { get; set; }
        public string SecurityType { get; set; }
        public string GrossTradeAmt { get; set; }
        public string PriceType { get; set; }
        public string MultiLegReportingType { get; set; }
        public string TradeReportTransType { get; set; }
        public string TradeReportID { get; set; }
        public string MatchStatus { get; set; }
        public string MatchType { get; set; }
        public string TradeLinkID { get; set; }
        public string TrdType { get; set; }
        public string TradeReportType { get; set; }
        public string TradeID { get; set; }
        public string SecondaryTradeID { get; set; }
        public string LotType { get; set; }
        public string TradeHandlingInstr { get; set; }
        public string ApplID { get; set; }
        public string ApplSeqNum { get; set; }
        public string ProductComplex { get; set; }
        public string ApplLastSeqNum { get; set; }
        public string ApplResendFlag { get; set; }
        public string NumericOrderID { get; set; }
        public string PriceSetter { get; set; }
        public string NoSides { get; set; }
        public string Side { get; set; }
        public string OrderID { get; set; }
        public string ClOrdID { get; set; }
        public string Account { get; set; }
        public string AccountType { get; set; }
        public string OrderCapacity { get; set; }
        public string NetMoney { get; set; }
        public string OrderCategory { get; set; }
        public string SideExecID { get; set; }
        public string SideLiquidityInd { get; set; }
    }
}
