//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BymaFixTester.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BymaTrades
    {
        public int MarketTradeID { get; set; }
        public int MarketOrderID { get; set; }
        public int BymaOrderID { get; set; }
        public string MsgType { get; set; }
        public string ApplID { get; set; }
        public string ExecID { get; set; }
        public string ClOrdID { get; set; }
        public string MDEntryID { get; set; }
        public string OrigClOrdID { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> MultiLegReportingType { get; set; }
        public string SecondaryOrderID { get; set; }
        public string ExecType { get; set; }
        public string TrdMatchID { get; set; }
        public string ExecRefID { get; set; }
        public Nullable<int> ExecRestatementReason { get; set; }
        public string OrdStatus { get; set; }
        public string WorkingIndicator { get; set; }
        public string OrdRejReason { get; set; }
        public string Text { get; set; }
        public Nullable<int> LastQty { get; set; }
        public Nullable<double> LastPx { get; set; }
        public Nullable<double> LastParPx { get; set; }
        public string Yield { get; set; }
        public string AccruedInterestAmt { get; set; }
        public int LeavesQty { get; set; }
        public int CumQty { get; set; }
        public Nullable<double> AvgPx { get; set; }
        public string Symbol { get; set; }
        public string SecurityType { get; set; }
        public string Currency { get; set; }
        public string ParPx { get; set; }
        public string ConvertedYield { get; set; }
        public int OrderBook { get; set; }
        public Nullable<int> NoPartyIDs { get; set; }
        public Nullable<int> PartyID { get; set; }
        public string PartyIDSource { get; set; }
        public Nullable<int> PartyRole { get; set; }
        public string Account { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string OrdType { get; set; }
        public Nullable<int> TimeForce { get; set; }
        public string ExpireTime { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string NoTradingSessions { get; set; }
        public string TradingSessionID { get; set; }
        public string ExecInst { get; set; }
        public int Side { get; set; }
        public int OrderQty { get; set; }
        public Nullable<int> DisplayQty { get; set; }
        public Nullable<int> DisplayMethod { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> StopPx { get; set; }
        public Nullable<int> PegOffsetValue { get; set; }
        public string PreTradeAnonymity { get; set; }
        public string OrderCapacity { get; set; }
        public string ClOrdLinkID { get; set; }
        public string OrderSource { get; set; }
        public string TransactTime { get; set; }
        public Nullable<int> SettlType { get; set; }
        public string SettlDate { get; set; }
        public bool PriceSetter { get; set; }
        public int NumericOrderID { get; set; }
        public string RFQID { get; set; }
        public int SecondaryTradeID { get; set; }
        public int SecurityID { get; set; }
        public string SecurityIDSource { get; set; }
        public string TradeFlag { get; set; }
        public Nullable<int> TimeInForce { get; set; }
    }
}
