//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INOMSupport.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INOMSupport.Resources.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se insertó la Orden.
        /// </summary>
        internal static string OMS0001 {
            get {
                return ResourceManager.GetString("OMS0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar cargar las especies.
        /// </summary>
        internal static string OMS0002 {
            get {
                return ResourceManager.GetString("OMS0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay tenencia para promocionar.
        /// </summary>
        internal static string OMS0003 {
            get {
                return ResourceManager.GetString("OMS0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de ejecución[{0}] no es un día hábil..
        /// </summary>
        internal static string OMS0004 {
            get {
                return ResourceManager.GetString("OMS0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad no implementada.
        /// </summary>
        internal static string OMS0005 {
            get {
                return ResourceManager.GetString("OMS0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de solicitud inválido.
        /// </summary>
        internal static string OMS0006 {
            get {
                return ResourceManager.GetString("OMS0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La orden no se puede cancelar porque no está pendiente o ya se encuentra completada.
        /// </summary>
        internal static string OMS0007 {
            get {
                return ResourceManager.GetString("OMS0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelación de la orden en progreso.
        /// </summary>
        internal static string OMS0008 {
            get {
                return ResourceManager.GetString("OMS0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden {0} existente en OMS.
        /// </summary>
        internal static string OMS0009 {
            get {
                return ResourceManager.GetString("OMS0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha llegado al tiempo máximo en el reciclo de la orden.
        /// </summary>
        internal static string OMS0010 {
            get {
                return ResourceManager.GetString("OMS0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar crear la prenota.
        /// </summary>
        internal static string OMS0011 {
            get {
                return ResourceManager.GetString("OMS0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar generar el comprobante.
        /// </summary>
        internal static string OMS0012 {
            get {
                return ResourceManager.GetString("OMS0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Calypso.
        /// </summary>
        internal static string OMS0013 {
            get {
                return ResourceManager.GetString("OMS0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo información de calendarios.
        /// </summary>
        internal static string OMS0014 {
            get {
                return ResourceManager.GetString("OMS0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo información de especies.
        /// </summary>
        internal static string OMS0015 {
            get {
                return ResourceManager.GetString("OMS0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error validando la orden programada.
        /// </summary>
        internal static string OMS0016 {
            get {
                return ResourceManager.GetString("OMS0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametros inválidos en mensaje de entrada al servicio.
        /// </summary>
        internal static string OMS0017 {
            get {
                return ResourceManager.GetString("OMS0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error ingresando instrucción de cancelación.
        /// </summary>
        internal static string OMS0018 {
            get {
                return ResourceManager.GetString("OMS0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error ingresando instrucción de promoción.
        /// </summary>
        internal static string OMS0019 {
            get {
                return ResourceManager.GetString("OMS0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error ingresando instrucción de transferencia.
        /// </summary>
        internal static string OMS0020 {
            get {
                return ResourceManager.GetString("OMS0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en asignación de precio. Precio no actualizado..
        /// </summary>
        internal static string OMS0021 {
            get {
                return ResourceManager.GetString("OMS0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una orden con mismo número de referencia.
        /// </summary>
        internal static string OMS0022 {
            get {
                return ResourceManager.GetString("OMS0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error fondo inexistente.
        /// </summary>
        internal static string OMS0023 {
            get {
                return ResourceManager.GetString("OMS0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inválida, no se permite cambiar la fecha.
        /// </summary>
        internal static string OMS0024 {
            get {
                return ResourceManager.GetString("OMS0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Ingresando Instrucción Permanente.
        /// </summary>
        internal static string OMS0025 {
            get {
                return ResourceManager.GetString("OMS0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Ingresando Scheduler.
        /// </summary>
        internal static string OMS0026 {
            get {
                return ResourceManager.GetString("OMS0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos inválidos en el ingreso de Scheduler.
        /// </summary>
        internal static string OMS0027 {
            get {
                return ResourceManager.GetString("OMS0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INOMCore service is not available.
        /// </summary>
        internal static string OMS0028 {
            get {
                return ResourceManager.GetString("OMS0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INOMSmartRouting service is not available.
        /// </summary>
        internal static string OMS0029 {
            get {
                return ResourceManager.GetString("OMS0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INOMMarketFunds service is not available.
        /// </summary>
        internal static string OMS0030 {
            get {
                return ResourceManager.GetString("OMS0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INOMBackOffice service is not available.
        /// </summary>
        internal static string OMS0031 {
            get {
                return ResourceManager.GetString("OMS0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rabbit Service is not available.
        /// </summary>
        internal static string OMS0032 {
            get {
                return ResourceManager.GetString("OMS0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden Inexistente.
        /// </summary>
        internal static string OMS0033 {
            get {
                return ResourceManager.GetString("OMS0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un calendario asociado al fondo.
        /// </summary>
        internal static string OMS0034 {
            get {
                return ResourceManager.GetString("OMS0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INOMFeeMgt service is not available.
        /// </summary>
        internal static string OMS0035 {
            get {
                return ResourceManager.GetString("OMS0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INOMReceipt service is not available.
        /// </summary>
        internal static string OMS0036 {
            get {
                return ResourceManager.GetString("OMS0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos de Calypso para generar comprobante.
        /// </summary>
        internal static string OMS0037 {
            get {
                return ResourceManager.GetString("OMS0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener el parametro SAP_SERVICE_ACCOUNT.
        /// </summary>
        internal static string OMS0038 {
            get {
                return ResourceManager.GetString("OMS0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo información de Simple Transfers.
        /// </summary>
        internal static string OMS0039 {
            get {
                return ResourceManager.GetString("OMS0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creando mensaje para iTex.
        /// </summary>
        internal static string OMS0040 {
            get {
                return ResourceManager.GetString("OMS0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en respuesta del servicio BT.
        /// </summary>
        internal static string OMS0041 {
            get {
                return ResourceManager.GetString("OMS0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error validando la instrucción de cancelación.
        /// </summary>
        internal static string OMS0042 {
            get {
                return ResourceManager.GetString("OMS0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creando mensaje para BT.
        /// </summary>
        internal static string OMS0043 {
            get {
                return ResourceManager.GetString("OMS0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INOMFeeds service is not available.
        /// </summary>
        internal static string OMS0044 {
            get {
                return ResourceManager.GetString("OMS0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar cancelar la prenota.
        /// </summary>
        internal static string OMS0045 {
            get {
                return ResourceManager.GetString("OMS0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de orden inválido.
        /// </summary>
        internal static string OMS0046 {
            get {
                return ResourceManager.GetString("OMS0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo información de Calypso para generar comprobante.
        /// </summary>
        internal static string OMS0047 {
            get {
                return ResourceManager.GetString("OMS0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo Simple Transfer, campo hostId es igual a null.
        /// </summary>
        internal static string OMS0048 {
            get {
                return ResourceManager.GetString("OMS0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametros inválidos - El importe y la cantida de cuotapartes no pueden ser mutuamente cero..
        /// </summary>
        internal static string OMS0049 {
            get {
                return ResourceManager.GetString("OMS0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en respuesta del servicio Listar Cotizaciones Diarias.
        /// </summary>
        internal static string OMS0050 {
            get {
                return ResourceManager.GetString("OMS0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El instrumento se encuentra desactivado para operar.
        /// </summary>
        internal static string OMS0100 {
            get {
                return ResourceManager.GetString("OMS0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El instrumento no opera con esa moneda.
        /// </summary>
        internal static string OMS0101 {
            get {
                return ResourceManager.GetString("OMS0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El instrumento no opera con ese tipo de orden.
        /// </summary>
        internal static string OMS0102 {
            get {
                return ResourceManager.GetString("OMS0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El instrumento no opera con ese TimeInForce.
        /// </summary>
        internal static string OMS0103 {
            get {
                return ResourceManager.GetString("OMS0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El instrumento no opera con ese SecurityType.
        /// </summary>
        internal static string OMS0104 {
            get {
                return ResourceManager.GetString("OMS0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El instrumento no opera con ese SettlmntTyp.
        /// </summary>
        internal static string OMS0105 {
            get {
                return ResourceManager.GetString("OMS0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener la lista de instrumentos para insertar en la tabla InstrumentsByma.
        /// </summary>
        internal static string OMS0106 {
            get {
                return ResourceManager.GetString("OMS0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción no controlada.
        /// </summary>
        internal static string OMS9999 {
            get {
                return ResourceManager.GetString("OMS9999", resourceCulture);
            }
        }
    }
}
